language: c
sudo: false
cache:
  directories:
  - ~/arduino_ide
  - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
env:
  global:
  - PRETTYNAME="ServoEasing Arduino Library"
before_install:
- source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
# do not know why this is needed here, for Talkie and other repos it works without this line
  - ln -s $PWD /home/travis/arduino_ide/libraries/ServoEasing
script:
- build_platform uno
- build_platform leonardo
- build_platform cplayClassic
- build_platform mega2560
notifications:
  email:
    on_success: change
    on_failure: always