# LibraryBuild.yml
# Github workflow script to test compile all examples of an Arduino library repository.
#
# Copyright (C) 2020  Armin Joachimsmeyer
# https://github.com/ArminJo/Github-Actions
#

# This is the name of the workflow, visible on GitHub UI.
name: LibraryBuild
on: [push, pull_request] # see: https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request

jobs:
  build:
    name: ${{ matrix.arduino-boards-fqbn }} - test compiling examples

    runs-on: ubuntu-latest # I picked Ubuntu to use shell scripts.

    env:
      # Space separated list without double quotes around the list. 
      # If you need a library with a space in its name, like Adafruit NeoPixel or Adafruit INA219, you must use double quotes
      # around the name and have at least 2 entries, where the first must be without double quotes! You may use Servo as dummy entry.
      REQUIRED_LIBRARIES: Servo ESP32Servo

    strategy:
      matrix:
        # The matrix will produce one job for each configuration parameter of type `arduino-boards-fqbn`
        # In the Arduino IDE, the fqbn is printed in the first line of the verbose output for compilation as parameter -fqbn=... for the "arduino-builder -dump-prefs" command
        #
        # Examples: arduino:avr:uno, arduino:avr:leonardo, arduino:avr:nano, arduino:avr:mega
        # arduino:sam:arduino_due_x, arduino:samd:arduino_zero_native"
        # ATTinyCore:avr:attinyx5:chip=85,clock=1internal, digistump:avr:digispark-tiny, digistump:avr:digispark-pro
        # STM32:stm32:GenF1:pnum=BLUEPILL_F103C8
        # esp8266:esp8266:huzzah:eesz=4M3M,xtal=80, esp32:esp32:featheresp32:FlashFreq=80
        # You may add a suffix behind the fqbn with "|" to specify one board for e.g. different compile options like arduino:avr:uno|trace 
        #############################################################################################################
        arduino-boards-fqbn:
          - arduino:avr:uno
          - arduino:avr:leonardo
          - arduino:avr:mega
          - arduino:sam:arduino_due_x
          - esp8266:esp8266:huzzah:eesz=4M3M,xtal=80
          - esp32:esp32:featheresp32:FlashFreq=80
          - STM32:stm32:GenF1:pnum=BLUEPILL_F103C8

        # Specify parameters for each board.
        # Parameters can be: platform-url, examples-exclude and examples-build-properties
        # With examples-exclude you may exclude specific examples for a board. Use a space separated list.
        #############################################################################################################
        include:
          - arduino-boards-fqbn: arduino:avr:uno
            examples-build-properties: # the flags were put in compiler.cpp.extra_flags
              SymmetricEasing:
                -DKEEP_SERVO_EASING_LIBRARY_SMALL
                -DDEBUG
              AsymmetricEasing:
                -DTRACE
              Simple:
                -DPRINT_FOR_SERIAL_PLOTTER
              TwoServos:
                -DUSE_LEIGHTWEIGHT_SERVO_LIB                
              ThreeServos:
                -DPROVIDE_ONLY_LINEAR_MOVEMENT
              PCA9685_Expander:
                -DUSE_PCA9685_SERVO_EXPANDER
              PCA9685_ExpanderFor32Servos:
                -DUSE_PCA9685_SERVO_EXPANDER
                -DMAX_EASING_SERVOS=32
                -DTRACE

          - arduino-boards-fqbn: arduino:avr:leonardo
            examples-build-properties:
              PCA9685_Expander:
                -DUSE_PCA9685_SERVO_EXPANDER
              PCA9685_ExpanderFor32Servos:
                -DUSE_PCA9685_SERVO_EXPANDER
                -DMAX_EASING_SERVOS=32
                -DTRACE

          - arduino-boards-fqbn: arduino:avr:mega
            examples-build-properties:
              PCA9685_Expander:
                -DUSE_PCA9685_SERVO_EXPANDER
              PCA9685_ExpanderFor32Servos:
                -DUSE_PCA9685_SERVO_EXPANDER
                -DMAX_EASING_SERVOS=32
                -DTRACE

          - arduino-boards-fqbn: arduino:sam:arduino_due_x
            examples-exclude: QuadrupedControl RobotArmControl # QuadrupedControl RobotArmControl because of missing EEprom
            examples-build-properties:
              PCA9685_Expander:
                -DUSE_PCA9685_SERVO_EXPANDER
              PCA9685_ExpanderFor32Servos:
                -DUSE_PCA9685_SERVO_EXPANDER
                -DMAX_EASING_SERVOS=32
                -DTRACE

          - arduino-boards-fqbn: esp8266:esp8266:huzzah:eesz=4M3M,xtal=80
            platform-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
            examples-exclude: QuadrupedControl RobotArmControl SpeedTest # SpeedTest because of only one analog input
            examples-build-properties:
              PCA9685_Expander:
                -DUSE_PCA9685_SERVO_EXPANDER
              PCA9685_ExpanderFor32Servos:
                -DUSE_PCA9685_SERVO_EXPANDER
                -DMAX_EASING_SERVOS=32
                -DTRACE

          - arduino-boards-fqbn: esp32:esp32:featheresp32:FlashFreq=80
            platform-url: https://dl.espressif.com/dl/package_esp32_index.json
            examples-exclude: QuadrupedControl RobotArmControl # Space separated list of (unique substrings of) example names to exclude in build
            examples-build-properties:
              PCA9685_Expander:
                -DUSE_PCA9685_SERVO_EXPANDER
              PCA9685_ExpanderFor32Servos:
                -DUSE_PCA9685_SERVO_EXPANDER
                -DMAX_EASING_SERVOS=32
                -DTRACE

          - arduino-boards-fqbn: STM32:stm32:GenF1:pnum=BLUEPILL_F103C8
            platform-url: https://github.com/stm32duino/BoardManagerFiles/raw/dev/STM32/package_stm_index.json
            examples-exclude: QuadrupedControl RobotArmControl
            examples-build-properties:
              PCA9685_Expander:
                -DUSE_PCA9685_SERVO_EXPANDER
              PCA9685_ExpanderFor32Servos:
                -DUSE_PCA9685_SERVO_EXPANDER
                -DMAX_EASING_SERVOS=32
                -DTRACE

      # Do not cancel all jobs / architectures if one job fails
      fail-fast: false

    # This is the list of steps this job will run.
    steps:

      # First of all, we clone the repo using the `checkout` action.
      - name: Checkout
        uses: actions/checkout@master

      - name: Compile all examples
        uses: ArminJo/arduino-test-compile@master
        with:
          arduino-board-fqbn: ${{ matrix.arduino-boards-fqbn }}
          platform-url: ${{ matrix.platform-url }}
          required-libraries: ${{ env.REQUIRED_LIBRARIES }}
          examples-exclude: ${{ matrix.examples-exclude }}
          examples-build-properties: ${{ toJson(matrix.examples-build-properties) }}
